//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookAddInOVA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool prmCreateZUnOVA {
            get {
                return ((bool)(this["prmCreateZUnOVA"]));
            }
            set {
                this["prmCreateZUnOVA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool prmCreateZUnFromMe {
            get {
                return ((bool)(this["prmCreateZUnFromMe"]));
            }
            set {
                this["prmCreateZUnFromMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmSmartFastFormulirovka {
            get {
                return ((string)(this["prmSmartFastFormulirovka"]));
            }
            set {
                this["prmSmartFastFormulirovka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmSmartFastKriterii {
            get {
                return ((string)(this["prmSmartFastKriterii"]));
            }
            set {
                this["prmSmartFastKriterii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmSmartExecutorFormulirovka {
            get {
                return ((string)(this["prmSmartExecutorFormulirovka"]));
            }
            set {
                this["prmSmartExecutorFormulirovka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmSmartExecutorKriterii {
            get {
                return ((string)(this["prmSmartExecutorKriterii"]));
            }
            set {
                this["prmSmartExecutorKriterii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool prmCreateOtherZUn {
            get {
                return ((bool)(this["prmCreateOtherZUn"]));
            }
            set {
                this["prmCreateOtherZUn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool prmCreateSMART {
            get {
                return ((bool)(this["prmCreateSMART"]));
            }
            set {
                this["prmCreateSMART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmZUnDopRazrez {
            get {
                return ((string)(this["prmZUnDopRazrez"]));
            }
            set {
                this["prmZUnDopRazrez"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmZUnButtonName {
            get {
                return ((string)(this["prmZUnButtonName"]));
            }
            set {
                this["prmZUnButtonName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prmPodrazdTo {
            get {
                return ((string)(this["prmPodrazdTo"]));
            }
            set {
                this["prmPodrazdTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool prmCreateZUnTO {
            get {
                return ((bool)(this["prmCreateZUnTO"]));
            }
            set {
                this["prmCreateZUnTO"] = value;
            }
        }
    }
}
